# Generated by Django 4.1.10 on 2023-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_tag_post_date_created_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
