# Generated by Django 4.1.10 on 2023-10-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_post_cover_image_post_is_complete_post_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(null=True, to="posts.tag"),
        ),
    ]
