# Generated by Django 4.1.10 on 2023-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_post_tag_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="Use markdown to writing content, You can find the guide at <a href=''https://www.markdownguide.org/cheat-sheet/>here</a> "
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
