# Generated by Django 4.1.10 on 2023-10-18 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0007_alter_post_content_alter_post_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="user_likes_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="Use markdown to writing content, You can find the guide at <a target='_blank' href='https://www.markdownguide.org/cheat-sheet/'>here</a> "
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                null=True, related_name="post_tags_set", to="posts.tag"
            ),
        ),
    ]
