# Generated by Django 4.1.10 on 2023-10-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "posts",
            "0009_reportpost_alter_post_options_alter_post_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportpost",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="GroupPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=250)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("post", models.ManyToManyField(to="posts.post")),
            ],
        ),
    ]
