# Generated by Django 4.1.10 on 2023-10-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_reportpost_description_grouppost"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpost",
            name="report_name",
            field=models.CharField(
                choices=[
                    ("Unappropriate content", "Unappropriate content"),
                    ("Another report", "Another report"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
