# Generated by Django 4.1.10 on 2023-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_reportpost_report_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpost",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_tags_set",
                to="posts.tag",
            ),
        ),
        migrations.AlterField(
            model_name="reportpost",
            name="description",
            field=models.TextField(
                default="", verbose_name="Report description"
            ),
        ),
    ]
