# Generated by Django 4.1.10 on 2023-10-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_reportpost_is_read_alter_post_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppost",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.grouppost",
            ),
        ),
        migrations.AlterField(
            model_name="reportpost",
            name="report_name",
            field=models.CharField(
                choices=[
                    ("Unappropriate content", "Unappropriate content"),
                    ("Another report", "Another report"),
                ],
                max_length=50,
                null=True,
                verbose_name="Report reason",
            ),
        ),
    ]
