# Generated by Django 4.1.10 on 2023-10-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_hide",
            field=models.BooleanField(default=False),
        ),
    ]
