# Generated by Django 4.1.10 on 2023-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_post_is_hide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_hide",
            field=models.BooleanField(default=False, verbose_name="Hide post"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
