# Generated by Django 4.1.10 on 2023-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_alter_post_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_nsfw",
            field=models.BooleanField(
                default=False, verbose_name="Flag your post as an nsfw post"
            ),
        ),
    ]
