# Generated by Django 4.1.10 on 2023-10-28 00:22

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0022_alter_reportpost_user_reportcommentpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentpost",
            name="date_created",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commentpost",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="comment_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
