# Generated by Django 4.1.10 on 2023-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_commentpost_date_created_commentpost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
