# Generated by Django 4.1.10 on 2023-10-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0026_tag_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="css_class",
            field=models.CharField(
                default="tag_blue_100", max_length=50, null=True
            ),
        ),
    ]
