# Generated by Django 4.1.10 on 2023-10-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0027_alter_tag_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="css_class",
            field=models.CharField(default="e", max_length=50, null=True),
        ),
    ]
