# Generated by Django 4.1.10 on 2023-10-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0030_alter_tag_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="css_class",
            field=models.CharField(
                default="tag_blue_250\n",
                editable=False,
                max_length=50,
                null=True,
            ),
        ),
    ]
