# Generated by Django 4.1.10 on 2023-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0031_alter_tag_css_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="group",
        ),
        migrations.AddField(
            model_name="grouppost",
            name="posts",
            field=models.ManyToManyField(
                related_name="group_post_set", to="posts.post"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="css_class",
            field=models.CharField(
                choices=[
                    ("tag_blue_100", "tag_blue_100"),
                    ("tag_blue_150", "tag_blue_150"),
                    ("tag_green_100", "tag_green_100"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
