# Generated by Django 4.1.10 on 2023-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0033_postseries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppost",
            name="posts",
            field=models.ManyToManyField(
                related_name="group_post_set",
                through="posts.PostSeries",
                to="posts.post",
            ),
        ),
    ]
