# Generated by Django 4.1.10 on 2023-10-29 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0033_postseries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppost",
            name="posts",
        ),
        migrations.DeleteModel(
            name="PostSeries",
        ),
    ]
