# Generated by Django 4.1.10 on 2023-10-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0034_remove_grouppost_posts_delete_postseries"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_order", models.IntegerField(default=1)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.grouppost",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grouppost",
            name="posts",
            field=models.ManyToManyField(
                related_name="group_post_set",
                through="posts.PostSeries",
                to="posts.post",
            ),
        ),
    ]
