# Generated by Django 4.1.10 on 2023-10-29 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0034_alter_grouppost_posts"),
        ("posts", "0035_postseries_grouppost_posts"),
    ]

    operations = []
