# Generated by Django 4.1.10 on 2023-10-30 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0036_merge_20231029_0950"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppost",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="chapter_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posts.grouppost",
            ),
        ),
    ]
