# Generated by Django 4.1.10 on 2023-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0037_remove_grouppost_posts_post_chapter_id_post_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="chapter_id",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
