# Generated by Django 4.1.10 on 2023-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0038_alter_post_chapter_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AlterField(
            model_name="post",
            name="chapter_id",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
