# Generated by Django 4.1.10 on 2023-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0040_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Post summary"
            ),
        ),
    ]
