# Generated by Django 4.1.10 on 2023-10-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0041_post_summary"),
    ]

    operations = []
