# Generated by Django 4.1.10 on 2023-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0042_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="This site are using markdown to writing content, You can find the guide at <a target='_blank' href='https://www.markdownguide.org/cheat-sheet/'>here</a> ",
                null=True,
            ),
        ),
    ]
