# Generated by Django 4.1.10 on 2023-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0045_alter_post_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_complete",
            field=models.BooleanField(
                default=False, verbose_name="Set your post as complete"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(
                default=True, verbose_name="Set your post as draft"
            ),
        ),
    ]
