# Generated by Django 4.1.10 on 2023-11-03 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0048_rename_date_publish_post_date_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_published"]},
        ),
    ]
