# Generated by Django 4.1.10 on 2023-11-07 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0049_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_published", "-date_updated"]},
        ),
        migrations.AddField(
            model_name="grouppost",
            name="followers",
            field=models.ManyToManyField(
                default=True,
                null=True,
                related_name="follower_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
