# Generated by Django 4.1.10 on 2023-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0050_alter_post_options_grouppost_followers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": [
                    "-date_published",
                    "-date_created",
                    "-date_updated",
                ]
            },
        ),
        migrations.RenameField(
            model_name="reportcommentpost",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="reportpost",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="reportpost",
            old_name="report_name",
            new_name="reason",
        ),
        migrations.AddField(
            model_name="reportcommentpost",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reportcommentpost",
            name="description",
            field=models.TextField(
                default="", verbose_name="Report description"
            ),
        ),
        migrations.AlterField(
            model_name="reportcommentpost",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Unappropriate content", "Unappropriate content"),
                    ("Another report", "Another report"),
                ],
                max_length=50,
                null=True,
                verbose_name="Report reason",
            ),
        ),
    ]
