# Generated by Django 4.2.7 on 2023-11-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_alter_post_options_and_more'),
    ]

    operations = [
    ]
