# Generated by Django 4.2.7 on 2023-11-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_delete_postcontent_reportcommentpost_date_created_and_more'),
    ]

    operations = [
    ]
