# Generated by Django 4.2.7 on 2023-11-15 01:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_delete_postcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='css_class',
        ),
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0088ffd0', image_field=None, max_length=25, samples=None),
        ),
    ]
