# Generated by Django 4.2.7 on 2023-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_delete_postcontent_remove_tag_css_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
