# Generated by Django 4.2.7 on 2023-11-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_delete_postcontent_alter_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
