# Generated by Django 4.2.7 on 2023-11-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_delete_postcontent_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
