# Generated by Django 4.2.7 on 2023-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_delete_postcontent_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='admin_tag',
            field=models.BooleanField(default=True),
        ),
    ]
