# Generated by Django 4.2.7 on 2023-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_delete_postcontent_tag_admin_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='admin_tag',
            field=models.BooleanField(default=False),
        ),
    ]
