# Generated by Django 4.1.10 on 2023-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(
                default="description of the role", max_length=100
            ),
        ),
    ]
