# Generated by Django 4.1.10 on 2023-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_ban_user_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.TextField(
                blank=True,
                help_text="Tell about yourself(max: 250 characthers)",
                max_length=250,
                null=True,
                verbose_name="User profile",
            ),
        ),
    ]
