# Generated by Django 4.1.10 on 2023-10-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_options_alter_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_liked_post",
            field=models.BooleanField(default=False),
        ),
    ]
