# Generated by Django 4.1.10 on 2023-10-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_allow_nsfw_user_show_liked_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="allow_nsfw",
            field=models.BooleanField(
                default=False, verbose_name="Allow nsfw posts"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_liked_post",
            field=models.BooleanField(
                default=False, verbose_name="Show your liked posts publicly"
            ),
        ),
    ]
