# Generated by Django 4.1.10 on 2023-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_email_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmed_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
