# Generated by Django 4.1.10 on 2023-11-04 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_confirmed_by_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="confirmed_by_admin",
            new_name="account_confirmed",
        ),
    ]
