# Generated by Django 4.1.10 on 2023-11-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_group_alter_user_groups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
