# Generated by Django 4.2.7 on 2023-11-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userban'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='ban_period',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
