# Generated by Django 4.2.7 on 2023-11-12 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userban_ban_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='ban_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userban',
            name='ban_category',
            field=models.CharField(choices=[('SPAM', 'Spamming'), ('ABUSE', 'Abusive Behavior'), ('HARASSMENT', 'Harassment'), ('THREATS', 'Threats of Violence'), ('IMPERSONATION', 'Impersonation'), ('COPYRIGHT_INFRINGEMENT', 'Copyright Infringement'), ('CHEATING', 'Cheating'), ('VIOLATING_TERMS_OF_SERVICE', 'Violating Terms of Service'), ('OTHER', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userban',
            name='ban_period',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('24h', '24 Hours'), ('7d', '7 Days'), ('30d', '30 Days'), ('perma', 'Permanent')], max_length=50),
        ),
    ]
