# Generated by Django 4.2.7 on 2023-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userban_ban_created_alter_userban_ban_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userban',
            options={'ordering': ['-ban_created']},
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
    ]
